"""
Bundles the fonts and logo used by the share images (src/lib/og.tsx) into
src/lib/og-assets.ts, so the images can be drawn on Cloudflare Workers,
which can't read files from disk.

Run again after changing the logo (brand/make-logos.py does this for you):
    python3 scripts/make-og-assets.py      # needs Pillow and npm install
"""
import base64
import io
from pathlib import Path

from PIL import Image

ROOT = Path(__file__).resolve().parent.parent
FONTS = ROOT / "node_modules/@fontsource/red-hat-display/files"
LOGO = ROOT / "src/assets/logo-horizontal-white.png"
OUT = ROOT / "src/lib/og-assets.ts"


def b64(data: bytes) -> str:
    return base64.b64encode(data).decode("ascii")


# The logo is drawn 507px wide; store it at that size to keep the file small.
logo = Image.open(LOGO)
logo = logo.resize((507, round(logo.height * 507 / logo.width)), Image.LANCZOS)
buf = io.BytesIO()
logo.save(buf, "PNG", optimize=True)

OUT.write_text(
    "// Generated by scripts/make-og-assets.py. Don't edit by hand.\n"
    "// Fonts and logo for the share images, as base64.\n\n"
    f'export const display600 = "{b64((FONTS / "red-hat-display-latin-600-normal.woff").read_bytes())}";\n\n'
    f'export const display800 = "{b64((FONTS / "red-hat-display-latin-800-normal.woff").read_bytes())}";\n\n'
    f'export const logoPng = "{b64(buf.getvalue())}";\n'
)
print(f"Wrote {OUT.relative_to(ROOT)} ({OUT.stat().st_size // 1024} KB)")
